# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annons',
            options={'verbose_name': '\u0410\u043d\u043e\u043d\u0441', 'verbose_name_plural': '\u0410\u043d\u043e\u043d\u0441\u044b'},
        ),
        migrations.AlterField(
            model_name='annons',
            name='image',
            field=models.FileField(help_text='gif, jpg, png...', upload_to='banners', verbose_name='\u0424\u0430\u0439\u043b'),
        ),
        migrations.AlterField(
            model_name='annons',
            name='title',
            field=models.CharField(max_length=200, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='annons',
            name='url',
            field=models.URLField(blank=True, help_text='', verbose_name='URL'),
        ),
    ]
