# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner_adds', '0004_auto_20170319_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banneradds',
            name='url',
            field=models.URLField(blank=True, help_text='', verbose_name='URL'),
        ),
    ]
