# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True, help_text='', verbose_name='URL')),
                ('image', models.FileField(help_text='gif, jpg, png...', upload_to='banners', verbose_name='File')),
                ('height', models.PositiveIntegerField(verbose_name='Height')),
            ],
        ),
    ]
