# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': '\u041f\u0430\u0440\u0442\u043d\u0435\u0440', 'verbose_name_plural': '\u041f\u0430\u0440\u0442\u043d\u0435\u0440\u044b'},
        ),
        migrations.AlterField(
            model_name='partner',
            name='url',
            field=models.URLField(blank=True, help_text='', verbose_name='URL'),
        ),
    ]
