# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-18 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200, verbose_name='\u041e\u0442\u0432\u0435\u0442')),
                ('votes', models.IntegerField(default=0, verbose_name='\u041a\u043e\u043b-\u0432\u043e \u0433\u043e\u043b\u043e\u0441\u043e\u0432')),
            ],
            options={
                'verbose_name': '\u0412\u044b\u0431\u043e\u0440',
                'verbose_name_plural': '\u0412\u044b\u0431\u043e\u0440',
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200, verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441')),
                ('pub_date', models.DateTimeField(blank=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438')),
            ],
            options={
                'verbose_name': '\u041e\u043f\u0440\u043e\u0441',
                'verbose_name_plural': '\u041e\u043f\u0440\u043e\u0441\u044b',
            },
        ),
        migrations.AddField(
            model_name='choice',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Poll'),
        ),
    ]
