# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200, verbose_name='Slug')),
                ('image', models.FileField(help_text='jpg, png...', upload_to='logos', verbose_name='\u0424\u0430\u0439\u043b')),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logo',
            },
        ),
    ]
